#include "../include/keyboard.h"
#include "../include/irq.h"

u8 keyboard_layout_us[2][128] = {{KEY_NULL,
                                  KEY_ESC,
                                  '1',
                                  '2',
                                  '3',
                                  '4',
                                  '5',
                                  '6',
                                  '7',
                                  '8',
                                  '9',
                                  '0',
                                  '-',
                                  '=',
                                  KEY_BACKSPACE,
                                  KEY_TAB,
                                  'q',
                                  'w',
                                  'e',
                                  'r',
                                  't',
                                  'y',
                                  'u',
                                  'i',
                                  'o',
                                  'p',
                                  '[',
                                  ']',
                                  KEY_ENTER,
                                  0,
                                  'a',
                                  's',
                                  'd',
                                  'f',
                                  'g',
                                  'h',
                                  'j',
                                  'k',
                                  'l',
                                  ';',
                                  '\'',
                                  '`',
                                  0,
                                  '\\',
                                  'z',
                                  'x',
                                  'c',
                                  'v',
                                  'b',
                                  'n',
                                  'm',
                                  ',',
                                  '.',
                                  '/',
                                  0,
                                  0,
                                  0,
                                  ' ',
                                  0,
                                  KEY_F1,
                                  KEY_F2,
                                  KEY_F3,
                                  KEY_F4,
                                  KEY_F5,
                                  KEY_F6,
                                  KEY_F7,
                                  KEY_F8,
                                  KEY_F9,
                                  KEY_F10,
                                  0,
                                  0,
                                  KEY_HOME,
                                  KEY_UP,
                                  KEY_PAGE_UP,
                                  '-',
                                  KEY_LEFT,
                                  '5',
                                  KEY_RIGHT,
                                  '+',
                                  KEY_END,
                                  KEY_DOWN,
                                  KEY_PAGE_DOWN,
                                  KEY_INSERT,
                                  KEY_DELETE,
                                  0,
                                  0,
                                  0,
                                  KEY_F11,
                                  KEY_F12},
                                 {KEY_NULL,
                                  KEY_ESC,
                                  '!',
                                  '@',
                                  '#',
                                  '$',
                                  '%',
                                  '^',
                                  '&',
                                  '*',
                                  '(',
                                  ')',
                                  '_',
                                  '+',
                                  KEY_BACKSPACE,
                                  KEY_TAB,
                                  'Q',
                                  'W',
                                  'E',
                                  'R',
                                  'T',
                                  'Y',
                                  'U',
                                  'I',
                                  'O',
                                  'P',
                                  '{',
                                  '}',
                                  KEY_ENTER,
                                  0,
                                  'A',
                                  'S',
                                  'D',
                                  'F',
                                  'G',
                                  'H',
                                  'J',
                                  'K',
                                  'L',
                                  ':',
                                  '\"',
                                  '~',
                                  0,
                                  '|',
                                  'Z',
                                  'X',
                                  'C',
                                  'V',
                                  'B',
                                  'N',
                                  'M',
                                  '<',
                                  '>',
                                  '?',
                                  0,
                                  0,
                                  0,
                                  ' ',
                                  0,
                                  KEY_F1,
                                  KEY_F2,
                                  KEY_F3,
                                  KEY_F4,
                                  KEY_F5,
                                  KEY_F6,
                                  KEY_F7,
                                  KEY_F8,
                                  KEY_F9,
                                  KEY_F10,
                                  0,
                                  0,
                                  KEY_HOME,
                                  KEY_UP,
                                  KEY_PAGE_UP,
                                  '-',
                                  KEY_LEFT,
                                  '5',
                                  KEY_RIGHT,
                                  '+',
                                  KEY_END,
                                  KEY_DOWN,
                                  KEY_PAGE_DOWN,
                                  KEY_INSERT,
                                  KEY_DELETE,
                                  0,
                                  0,
                                  0,
                                  KEY_F11,
                                  KEY_F12}};

struct Keyboard keyboard = {0};

static void keyboard_handler(struct Registers *regs) {
  u16 scancode = (u16)inb(0x60);

  bool released = KEY_IS_RELEASE(scancode);
  u8 key = KEY_SCANCODE(scancode);

  keyboard.keys[key] = !released;

  bool shift = keyboard.keys[KEY_LSHIFT] || keyboard.keys[KEY_RSHIFT];

  if (released) {
    return;
  }

  u8 character = keyboard_layout_us[shift ? 1 : 0][key];
  if (character) {
    // tty_putc(character);
  } else if (key == KEY_ENTER) {
    // tty_putc('\n');
  } else if (key == KEY_BACKSPACE) {
  }
}

void keyboard_init() { irq_install(1, keyboard_handler); }
